theme = "hyde"
languageCode = "en-us"
baseurl = "http://mathsanddatanyu.github.io/"
title = "Math and Data"

[params]
	description = "Center for Data Science and Courant Institute, NYU"
	Author = "JB"
	##disqusShortname = "Joan"
