theme = "hydeold"
languageCode = "en-us"
baseurl = "https://mathsanddatanyu.github.io/website/"
title = "Math and Data"

[params]
	description = "Center for Data Science and Courant Institute, NYU"
	Author = "JB"
	##disqusShortname = "Joan"
